export enum COUNTER_TYPES {
  INCREMENT = "INCREMENT",
  DECREMENT = "DECREMENT",
  DEPOSIT = "DEPOSIT",
  WITHDRAW = "WITHDRAW",
}

export enum USERS_TYPES {
  ADD_USER = "ADD_USER",
  REMOVE_USER = "REMOVE_USER",
}
